services:
  mysql:
    build: ./mysql/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=output_db
    ports:
      - '3310:3306'
    volumes: 
      - ./mysqldata:/var/lib/mysql
    env_file: 
      - ./mysql/variables.env
     
volumes:
  mysqldata:
  mongodata:
